---
# CentOS
- name: create directory for unarchiving
  file:
    path: "{{ zabbix_agent_path }}"
    state: directory
- name: Extract bianries to CentOS servers
  ansible.builtin.unarchive:
    src: "{{ tar_packet_linux3 }}"
    dest: "{{ zabbix_agent_path }}"
- name: Ensure group "zabbix" exists
  ansible.builtin.group:
    name: "{{ zabbix_group }}"
    state: present
- name: Add "zabbix" user
  ansible.builtin.user:
    name: "{{ zabbix_user }}"
    comment: Zabbix
    group: "{{ zabbix_group }}"
- name: Change permissions and owner
  file:
    dest: "{{ item }}"
    owner: "{{ zabbix_user }}"
    group: "{{ zabbix_group }}"
    recurse: true 
    # supposed to set directories to 755 and files to 644
    mode: u=rwX,g=rX,o=rX
  with_items:
    - "{{ zabbix_agent_path }}"
- name: Template zabbix-agent config file
  ansible.builtin.template:
    src: zabbix_agentd.j2
    dest: "{{ zabbix_agent_path }}/zabbix_agentd.conf"
    owner: "{{ zabbix_user }}"
    group: "{{ zabbix_group }}"
    mode: '0644'
    notify:
      - zabbix-agent6 enable
      - zabbix-agent6 restart
