---
# tasks file for zabbix-agent6
- import_tasks: Debian.yml
  when: ansible_facts['distribution'] == "Debian"

- import_tasks: Ubuntu.yml
  when: ansible_facts['distribution'] == "Ubuntu"

- import_tasks: CentOS.yml
  when: ansible_facts['distribution'] == "CentOS"
