---
# tasks file for zabbix-agent6
- import_tasks: Debian.yml
  tags:
    - Debian
  when: ansible_facts['distribution'] == "Debian"

- import_tasks: Ubuntu.yml
  tags:
    - Ubuntu
  when: ansible_facts['distribution'] == "Ubuntu"

- import_tasks: CentOS.yml
  tags:
    - CentOS
  when: ansible_facts['distribution'] == "CentOS"
