---
# tasks file for zabbix-agent6
- name: Update and upgrade apt packages
  apt:
    update_cache: yes
  tags:
    - always
  when: ansible_facts['distribution'] == "Ubuntu" or ansible_facts['distribution'] == "Debian"

- name: Copy .deb package to target
  tags: 
    - copy
  ansible.builtin.copy:
    src: "{{ deb_packet_ubuntu }}"
    dest: "{{ deb_packet_tmp_path }}"
    owner: root
    group: root
    mode: '0644'
  when: ansible_facts['distribution'] == "Ubuntu"
  ignore_errors: no

- name: Install a .deb package
  tags: 
    - install
  ansible.builtin.apt:
    deb: "{{ deb_packet_tmp_path }}{{ deb_packet_ubuntu }}"
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Remove .deb file on target
  tags: 
    - clean
  ansible.builtin.file:
    path: "{{ deb_packet_tmp_path }}{{ deb_packet_ubuntu }}"
    state: absent

- name: Enable service zabbix-agent6 and ensure it is not masked
  tags: 
    - install
  ansible.builtin.systemd:
    name: zabbix-agent6
    enabled: yes
    masked: no
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Make sure a service unit is running
  tags: 
    - install
  ansible.builtin.systemd:
    state: started
    name: zabbix-agent6
  when: ansible_facts['distribution'] == "Ubuntu"

