---
- name: Update and upgrade apt packages on Ubuntu {{ ansible_distribution_release }}
  apt:
    update_cache: yes
  tags:
    - always
- name: Copy .deb package to target
  tags: 
    - copy
  ansible.builtin.copy:
    src: "{{ deb_packet_ubuntu }}"
    dest: "{{ deb_packet_tmp_path }}"
    owner: root
    group: root
    mode: '0644'
  ignore_errors: no
- name: Install a .deb package
  tags: 
    - install
  ansible.builtin.apt:
    deb: "{{ deb_packet_tmp_path }}{{ deb_packet_ubuntu }}"
    notify:
      - zabbix-agent6 enable
      - zabbix-agent6 restart
- name: Remove .deb file on target
  tags: 
    - clean
  ansible.builtin.file:
    path: "{{ deb_packet_tmp_path }}{{ deb_packet_ubuntu }}"
    state: absent

