---
- hosts: all
  tasks:
    - name: Copy .deb package to target
      ansible.builtin.copy:
        src: ./zabbix_agent-6.0.12-linux-3.0-amd64-static.deb
        dest: /root/
        owner: root
        group: root
        mode: '0644'
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: Install a .deb package
      ansible.builtin.apt:
        deb: /root/zabbix_agent-6.0.12-linux-3.0-amd64-static.deb
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: Remove .deb file on target
      ansible.builtin.file:
        path: /root/zabbix_agent-6.0.12-linux-3.0-amd64-static.deb
        state: absent

    - name: Enable service zabbix-agent6 and ensure it is not masked
      ansible.builtin.systemd:
        name: zabbix-agent6
        enabled: yes
        masked: no
    - name: Make sure a service unit is running
      ansible.builtin.systemd:
        state: started
        name: zabbix-agent6
