#!/bin/sh

set -e

case "$1" in
    purge)
        rm -fr /opt/zabbix/conf/zabbix_agentd
        rm -fr /opt/zabbix/zabbix-agent.log
#        rm -fr /run/zabbix

        # Can be removed after Wheezy:
        ucf --purge /opt/zabbix/conf/zabbix_agentd.conf || true
    ;;
esac

# Automatically added by dh_installinit/13.5.2ubuntu1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d zabbix-agent6 remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_ucf/13.5.2ubuntu1
if [ "$1" = "purge" ]; then
	for ext in .ucf-new .ucf-old .ucf-dist ""; do
		rm -f "/opt/zabbix/conf/zabbix_agentd.conf$ext"
	done
	
	if [ -x "`command -v ucf`" ]; then
		ucf --purge "/opt/zabbix/conf/zabbix_agentd.conf"
	fi
	if [ -x "`command -v ucfr`" ]; then
		ucfr --purge zabbix-agent "/opt/zabbix/conf/zabbix_agentd.conf"
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.5.2ubuntu1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.5.2ubuntu1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'zabbix-agent6.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'zabbix-agent6.service' >/dev/null || true
		deb-systemd-helper unmask 'zabbix-agent6.service' >/dev/null || true
	fi
fi
# End automatically added section

