#!/bin/sh

set -e

CONFFILE="/opt/zabbix/conf/zabbix_agentd.conf"
CONFFILE_DEST="/opt/zabbix/conf/zabbix_agentd.conf"



if [ "$1" = "configure" ]; then
    # Does the user 'zabbix' exist?
    if ! getent passwd zabbix > /dev/null 2>&1 ; then
        # Not yet. Create it.
        adduser --quiet --system --group --disabled-login --no-create-home --home /nonexistent zabbix
    fi

    chown zabbix:zabbix /opt/zabbix/ -R
fi



    # Use ucf to handle the zabbix_agentd.conf configuration file
    ucf $CONFFILE $CONFFILE_DEST
    ucfr zabbix-agent $CONFFILE_DEST

