#! /bin/sh
### BEGIN INIT INFO
# Provides:          zabbix-agent6
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start zabbix-agent6 daemon
# Description: Start zabbix-agent6 daemon
### END INIT INFO

NAME=zabbix_agentd6
DAEMON=/opt/zabbix/sbin/$NAME
CONFIG=/opt/zabbix/conf/zabbix_agentd.conf
# Exit if executable is not installed
[ -x $DAEMON ] || exit 0

DIR=/opt/zabbix
#PID=$DIR/$NAME.pid
RETRY=TERM/30/KILL/5

# Load the VERBOSE setting and other rcS variables
[ -f /etc/default/rcS ] && . /etc/default/rcS

# define LSB log_* functions.
. /lib/lsb/init-functions

_ev_ () {
  [ "$VERBOSE" = "yes" ] || eval $@
}

[ -d "$DIR" ] || mkdir "$DIR"
chown -R zabbix:zabbix "$DIR"
export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
     start-stop-daemon --start --quiet --exec $DAEMON -- -c $CONFIG
     start-stop-daemon --start --oknodo --exec $DAEMON -- -c $CONFIG 2>&1
  ;;
  stop)
    _ev_ log_action_begin_msg "$NAME stopping"
    R=$(start-stop-daemon --stop --exec $DAEMON --oknodo --retry=$RETRY 2>&1) \
    && _ev_ log_action_end_msg 0 \"$R\" \
    || _ev_ log_action_end_msg 1 \"$R\"
  ;;
  status)
    ## return status 0 if process is running.
    status_of_proc "$DAEMON" "$NAME"
  ;;
  restart|force-reload)
    $0 stop
    $0 start
  ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" >&2
    exit 1
  ;;
esac
